### ISSUE TITLE
How does tab sync work?

### ISSUE THREAD

**Issue by tessus** [marcelklehr/floccus#700] opened 2020-10-21 19:42 UTC
Can you please provide some info on how the tab sync works?

Let's say I have 2 browser windows with X and Y number of tabs open. Now I open a browser on another machine and sync the tabs. Will it open two browser windows with X and Y number of tabs?
What happens if I open a new tab on the first machine, wlil it be opened on the second (after sync)?

**Comment by marcelklehr** [comment] 2020-10-21 20:05
Yes, that's the idea. However, deletions (closing tabs) will not be propagated with a simple merge sync in the case of syncing tabs. Thus it's usually more useful to only sync up or down.

**Comment by tessus** [comment] 2020-10-23 03:09
Thanks a bunch for the reply.

However, I'm not entirely sure I understand why deletions wouldn;'r be propagated. With the bookmark sync they are, aren't they? So why not use the same algorithm? Unless I'm missing something...

**Comment by marcelklehr** [comment] 2020-10-23 09:16
The problem is that tab IDs aren't as stable as bookmark IDs making it harder to sync them.

**Comment by tessus** [comment] 2020-10-23 14:12
I see. Although I'm not quite sure I understand that either. What do you mean my stable? Would the id change, if you re-arranged the tabs. e.g. from left to right: [1] [2] 3] -> [3] [1] [2]

Anyway, I guess we can close this. Or you can leave it around for a bit so that people can find it more easily.

**Comment by candrapersada** [comment] 2021-02-14 03:46
is it possible to add a Tab Manager to set sync?

**Comment by marcelklehr** [comment] 2021-02-14 13:44
> is it possible to add a Tab Manager to set sync?

Can you explain what you mean by that?

**Comment by candrapersada** [comment] 2021-02-14 17:39
Have multiple tabs related to a subject that you want to look at later? tabs manager supports saving and restoring tab sets as saved windows for disync.

**Comment by marcelklehr** [comment] 2021-02-14 18:34
I don't think this is within the scope of this extension for now. If you need to save a session, use "bookmark all tabs" and sync those bookmarks, I'd say. :)

**Closed by marcelklehr** 2021-02-14 18:34 UTC
Labels: question

**Comment by candrapersada** [comment] 2021-02-16 10:17
add Tab Suspender
