### ISSUE TITLE
Synchronisation is no longer possible

### ISSUE THREAD

**Issue by derritter88** [marcelklehr/floccus#715] opened 2020-10-30 12:29 UTC
**Describe the bug**
Since today I get the error "It's not possible to move Places root folders."

**To Reproduce**
1. Do a synchronisation, works fine.
2. Wait.
3. Error appears.

It is possible to delete all bookmarks from Nextcloud and kick off a whole new synchronisation - this works but after the new, initial synchronisation the error appears again.

**Expected behavior**
Synchronisation should work with out any issues.

**Desktop (please complete the following information):**
 - OS: Win10 Pro for Worksation
 - Browser: Firefox
 - Browser Version: 82.0.2
 - Floccus version: 4.4.4
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [x] Debug log provided

**Additional context**

**Comment by derritter88** [comment] 2020-10-30 12:38
Debug log uploaded as requested

**Comment by marcelklehr** [comment] 2020-10-30 12:51
Duplicate of #657, patch will be release ASAP

**Closed by marcelklehr** 2020-10-30 12:51 UTC
Labels: bug
