### ISSUE TITLE
Sync errors and network errors

### ISSUE THREAD

**Issue by a575606** [marcelklehr/floccus#234] opened 2019-02-18 06:03 UTC
### Software versions

- Browser: Chrome / Firefox latest, Windows 10 64bit
- Nextcloud: 15.0.2
- Nextcloud Bookmarks app:	0.16.1 (just updated to .2, but haven't checked if that fixed the issue)
- Floccus: 3.2.6
- Floccus sync method: nextcloud-folders
  															

### Steps to reproduce

First of all, thank you for creating this software, it is just what I needed. And it nearly works perfectly, I just have a couple issues. 

1. Network error. Whenever I launch Chrome or Firefox, usually after not using for some time, or waking the pc from sleep, often Floccus has an error icon and the error is a Network Error, unable to connect to the server (or similar wording, sorry I forgot to copy it last time it happened). The network is connected, internet working, and if I click sync now it usually syncs successfully without issue. Otherwise, it doesn't seem to go away or try to reconnect throughout the browsing session. 

2. Sync issues. In some ways not having too many options to worry about is nice. However, sync doesn't always work as expected. I use a desktop pc and a laptop and alternate between chrome and firefox on each. Usually I use firefox on my home pc, and only use my laptop when traveling. So I might make a lot of changes to the bookmarks on my desktop firefox since the last time I ran a sync from my laptop running Chrome, for example. Running sync in those instances often creates errors, explained below. 

### Expected outcome
1. Would only expect an error icon to show up in the event there's an actual problem connecting to the server. I.e. after retrying every set number of minutes for a few times, or when manually running sync and it failing. Or, increase the frequency of retrying sync when there's a connection error. 

2. I expect, on opening a new browser, bookmarks to be synced exactly to the state of the last browser that was closed, or the state on the server if the most recently modified bookmark is on the server. If I delete a bookmark anywhere, I expect it would be deleted everywhere. 
...

### Actual outcome
1. If the browser is running, it seems to sync before the network is ready immediately on wake. Then generates the error. I assume eventually it will try again, but have waited as long as 20 min and always get impatient and manually click sync to clear the error. 

2. Especially when opening a browser that hasn't been synced in a while, often duplicate bookmarks get created. For example two identical bookmarks, one with www.domain.com as the link, the other with domain.com. Or if the title has changed, I'll have two bookmarks, one with the old and one with the new title. Sometimes bookmarks I deleted on get recreated. Usually Floccus will show a sync error when this happens, and if I manually click sync afterwards, that's when the errors appear. Sometimes I have to backup the set of bookmarks that's most current, completely clear bookmarks on all devices, then re-import and re-sync to fix the issue. 

...

### Debug log
Can I send by email?

**Comment by marcelklehr** [comment] 2019-02-18 14:48
> Would only expect an error icon to show up in the event there's an actual problem connecting to the server. I.e. after retrying every set number of minutes for a few times, or when manually running sync and it failing. Or, increase the frequency of retrying sync when there's a connection error.

This is an interesting idea. I'll think about this.

> For example two identical bookmarks, one with www.domain.com as the link, the other with domain.com.

This is an issue that was introduced only recently and should since have been fixed with v3.2.6 (see #231 )

> Can I send by email?

Sure :)

**Comment by a575606** [comment] 2019-02-18 20:32
Thanks and glad you like the idea about the network error. Any thoughts on the second issue? Glad to hear the www/domain problem was fixed. I'm not sure when 3.2.6 came out, but I'll keep an eye out if it still happens. Probably the bigger issue for me is the changed title duplicates and the restoring deleted bookmarks issue. Were those also fixed?

Where can I find your email address to send the log to?

thanks

**Comment by marcelklehr** [comment] 2019-02-18 21:00
I can't think of a reason for the changed title duplicates, except that it might be caused by native browser sync interfering. Do you have that turned on?

Restored deleted bookmarks has been a known issue that I've been trying to fix for some time. In this matter the logs will be most helpful. you can find my mail address on my profile page: https://github.com/marcelklehr

**Comment by a575606** [comment] 2019-02-19 04:35
For the title duplicates, maybe it's related to the www/domain duplicate problem and I just noticed the titles were different. I'll keep checking.

Good to know you're aware of the restored deleted issue. I'm not sure how your sync algorithm works. Are comparisons done individually per bookmark? I guess for me, the expected behavior would be the bookmarks would be considered more of a set, i.e. when I open a browser, I'd expect the bookmarks to sync to exactly match the set I had on the last browser I closed. 

I'm on my laptop, but thanks for the link. I'll send you the log when I'm on my desktop later.

**Comment by a575606** [comment] 2019-02-19 12:54
I just sent the logs. By the way today I recevied another www / domain duplicate running the latest version

**Comment by marcelklehr** [comment] 2019-02-28 13:14
> By the way today I recevied another www / domain duplicate running the latest version

Note, that there's a difference between noticing a duplicate and it being created. I think it's quite likely the duplicate has been there since the faulty version was installed and was noticed only recently. (Note that floccus cannot weed out all duplicates it erroneously created, but may leave behind a few of them.)

**Comment by marcelklehr** [comment] 2019-02-28 13:19
I sadly cannot find any instance you described as a bookmark being deleted, causing a sync error and then being added back. Do you by any chance remember the error message?

**Comment by a575606** [comment] 2019-03-04 14:30
Just wanted to send some follow up on this.  I wanted to reorganize some bookmarks in a folder this morning and I was curious how floccus would handle the sync, so I paid attention to the order I did things in. 

Just to make explaining this simple, here's a basic diagram

bookmarks
  folder 1
  folder 2
  folder 3 <---
    subfolder 1
       subfolder1bookmark 1
       subfolder2boookmark 2
    subfolder 2
    subfolder 3
    folder3bookmark 1
    folder3bookmark 2

The steps were, I opened Firefox and went to the bookmark manager. In folder3 I had several bookmarks directly in the folder and 3 subfolders, each containing a few bookmarks. I made a new subfolder (say subfolder4) with a new name and put the bookmarks that were in folder3's root to subfolder4. Then I moved the bookmarks in subfolder1 to the root of folder3. 

I then clicked sync in firefox, waited until floccus synced successfully, opened chrome and clicked sync, which also showed success. 

The result was, none of the changes were synced from Firefox to Nextcloud and therefore did not show up in Chrome. However both Firefox and Chrome showed success when manually synced. 

Unfortunately I was heading out for a trip and will be away for 2 weeks, and didn't get a chance to copy the log before leaving. However, perhaps replicating the steps might help track down the error? It seems to me the sync algorithm is missing something in the comparisons, or sync is done via cache which isn't getting refreshed fast enough, i'm not sure. But there's clearly something not quite right. Let me know if I can help figure out what it is.

**Comment by marcelklehr** [comment] 2019-03-04 16:59
Are you sure that all your clients are up to date? I cannot replicate this with v3.2.7

**Comment by a575606** [comment] 2019-03-04 18:52
All clients are set to auto update and the ones on my laptop are definitely 3.2.7. Will check my home pc when I get home to make sure those are up to date, but assume so. 

The problem is once things get out of sync, it's not always easy to track down where the problem originated. What I can say is, I've clearly seen the issue happen when reorganizing bookmarks yesterday, and today when syncing on a laptop I haven't used in a couple weeks. 

If the expected behavior is your bookmarks are synced exactly to the last state they were in, there's definitely still an issue, even in 3.2.7.

**Comment by marcelklehr** [comment] 2019-03-04 20:58
> All clients are set to auto update and the ones on my laptop are definitely 3.2.7. Will check my home pc when I get home to make sure those are up to date, but assume so.

I see.

> If the expected behavior is your bookmarks are synced exactly to the last state they were in, there's definitely still an issue, even in 3.2.7.

I suspect a part of the problem is to have longer periods without sync for some browsers. Making changes in a tree that hasn't been synced in a while causes the next sync to make potentially problematic decisions.

**Comment by marcelklehr** [comment] 2019-03-04 21:03
> For example, I'm afraid to run a sync from this browser because i'm afraid these duplicates will spread to all the other browsers
No express or implied warranty, but I'm confident those duplicates will be filtered out by floccus v3.2.6+

**Comment by a575606** [comment] 2019-03-05 11:23
It just seems to me it would be a lot easier treating bookmarks as a set rather then comparing them individually 1 by 1

**Comment by marcelklehr** [comment] 2019-03-05 19:07
> It just seems to me it would be a lot easier treating bookmarks as a set rather then comparing them individually 1 by 1

I understand where you're coming from and it would indeed be much easier. On the other hand, this would cause changes on one browser to override changes on a different browser, forcing either the developer or the user to utilize some kind of locking, which in my opinion is a terrible user experience.

I will do some fuzzy (wild move and deletion operations) testing soon to simulate difficult sync situations, which will likely reproduce some of the errors that you're facing.

**Comment by marcelklehr** [comment] 2019-03-23 13:14
I've released another patch. Feedback is appreciated :)

**Closed** 2019-03-31 22:08 UTC
Labels: waiting for more information
