### ISSUE TITLE
E022: Folder #7672[door handle spring] supposedly contains non-existent bookmark 62551

### ISSUE THREAD

**Issue by Simplenuity** [marcelklehr/floccus#581] opened 2020-06-23 12:25 UTC
**Describe the bug**
Syncing fails with the following error message:
`E022: Folder #7672[door handle spring] supposedly contains non-existent bookmark 62551`

**To Reproduce**
1. Start browser with add-on installed
OR
Install add-on in browser and add account
OR
Manually start sync process
2. See error

**Expected behavior**
Successfully syncing bookmarks with Nextcloud account. 

**Desktop (please complete the following information):**
 - OS: Linux Lite (based on Ubuntu)
 - Browser: Google Chrome, Firefox, Opera, Vivaldi
 - Browser Version: 83.0.4103.116 (Official Build) (64-bit), 77.0.1 (64-bit), 68.0.3618.173, 3.1.1929.40 (Stable channel) (64-bit)
 - Floccus version: 4.2.5
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 https://nextcloud.webo.hosting/
Unfortunately can't find any information about version

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://klehranlage.net/index.php/s/7nn82NSBsfQKdsJ

- [x ] Debug log provided

**Additional context**
* sync has been tried with "Merge..." as well as "Always overwrite... local changes"
* sync has been tried with existing sync folder as well as new folder

If there is any further information or testing required, please let me know.
Many thanks for your efforts!

**Comment by marcelklehr** [comment] 2020-06-27 15:00
If this happens in all your browsers, there may be something fishy going on on the server. The exact server version would be helpful. Perhaps send this issue to your hoster and ask them to weigh in.

**Comment by marcelklehr** [comment] 2020-06-30 14:29
This could also be due to a shared folder. Is the folder in question shared by a different user?

**Comment by Simplenuity** [comment] 2020-06-30 14:47
> If this happens in all your browsers, there may be something fishy going on on the server. The exact server version would be helpful. Perhaps send this issue to your hoster and ask them to weigh in.

I'll open a ticket with them

**Comment by Simplenuity** [comment] 2020-06-30 14:47
> This could also be due to a shared folder. Is the folder in question shared by a different user?

No, there is no shared folder involved.

**Comment by Simplenuity** [comment] 2020-07-01 08:02
> If this happens in all your browsers, there may be something fishy going on on the server. The exact server version would be helpful. Perhaps send this issue to your hoster and ask them to weigh in.

I did, here's their reply:

_The only information we can currently provide is **Nextcloud version (18.0.4) and Bookmarks app version (3.0.5)**.
It will be upgraded soon to latest version 18.
It is installed according to manuals for intends to host free accounts on Nextcloud (as is, without any changes to its code).
Until now we haven't received any complaints about non-working application provided by Nextcloud, for 3rd party apps we can't give any guarantee they will work.
Please note, this is not a test installation and it is not intended for testing and debugging and there might be some limitations that could potentially have some impact on floccus._

**Comment by Simplenuity** [comment] 2020-07-01 10:06
The mentioned update on the server side will happen on the weekend. I'd suggest to wait for the result before spending time on this issue. Especially as I just tested FLOCCUS (no change of setup on my end) with another Nexcloud provider (cloudamo) and it synced successfully!

**Comment by marcelklehr** [comment] 2020-07-01 11:16
> Bookmarks app version (3.0.5).

Yeah, that version is known to have issues. I definitely suggest updating to v3.0.12 or v3.2.1

**Comment by Simplenuity** [comment] 2020-07-02 07:11
They have meanwhile updated to the latest version of Bookmarks.
Same error message :( 
Where from here?

**Comment by Programie** [comment] 2020-07-08 08:31
I have exactly the same issue.

In my case, I initially configured the Nextcloud account in Chrome on Linux and successfully synced the bookmarks to Nextcloud. After that, I configured the same account in Chrome on macOS and tried to sync the bookmarks which failed with the same error "E022: Folder xxx supposedly contains non-existent bookmark xxx".

I'm using version 3.2.4 of the Bookmarks app on Nextcloud 19.0.0.

**Comment by Simplenuity** [comment] 2020-07-09 07:12
After the update to **Bookmark version 3.2.4** all mentioned browsers **sync successfully** with my setup.
I'll leave the ticket open toas @Programie is obviously still facing the issues...

Thanks for all your efforts!

**Comment by Programie** [comment] 2020-07-09 09:22
After initially setting the sync behavior to "Always overwrite and revert remote changes" I was able to sync my second client.

**Comment by ours1** [comment] 2020-07-17 13:46
I've got the same problem with FLOCCUS V4.2.5 and BOOKMARK 3.2.4
E022: Folder #-1[undefined] supposedly contains non-existent bookmark 0 
with firefox (I tried other folder within) in both computer, one with window and the other with Xunbuntu.
Otherwise the app is nice nice nice!

**Comment by marcelklehr** [comment] 2020-07-21 19:43
Good news! I think I've found the cause of this error. The fix will be in the next release of the bookmarks app. I'll leave this open till then.

**Comment by Simplenuity** [comment] 2020-07-22 12:59
Great! Thanks for your efforts!

**Comment by ours1** [comment] 2020-07-23 07:18
oh ! I'm keen to be able to going on organizing my bookmark collection, thank you !

**Comment by marcelklehr** [comment] 2020-07-23 10:32
:ship:

**Closed by marcelklehr** 2020-07-23 10:32 UTC
Labels: bug
