### ISSUE TITLE
Sync not showing up on Nextcloud

### ISSUE THREAD

**Issue by bernd-wechner** [marcelklehr/floccus#128] opened 2018-06-18 06:35 UTC
Should it? I'm curious. I sort of expected it to. Config is:

Nextcloud: 13 (latest NextCloudPi image updated and up to date)
NextCloudPi: v0.56.22
Bookmark App:  0.11.0
Browser: Firefox 60.0.2 (64bit)
Floccus: 2.2.8

Floccus passes all tests:

![image](https://user-images.githubusercontent.com/7296506/41521156-68893daa-7314-11e8-81e0-058897d9f43a.png)

Sync Now works without complaint:

![image](https://user-images.githubusercontent.com/7296506/41521310-f4efc1f6-7314-11e8-82d2-65d9af4b272f.png)

And yet Nextcloud shows no bookmarks:

![image](https://user-images.githubusercontent.com/7296506/41521365-30075c40-7315-11e8-8d34-001cc2208837.png)

I suspect this is normal and my expectation is wrong, but wonder if that's true and if so why? Should I not see my bookmarks in Nextcloud? I've only tried with the one browser for not to get a feel for it. And admit I'm perplexed.

**Comment by marcelklehr** [comment] 2018-06-18 16:13
Mh. This is definitely not the expected behaviour. I couldn't replicate this with Firefox 60.0.1, Bookmarks 0.11 and floccus 2.2.8, though :/

Are you logged in with the correct account in the UI? :D
In any case, a glance at the logs might help:

In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* in the console tab, clear the output
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by bernd-wechner** [comment] 2018-06-18 20:13
From Firefox:

```
Starting sync process for account bernd@https://nephele.thumbs.place  Account.js:128:6
TypeError: ownerWin.whereToOpenLink is not a function[Learn More]  WebNavigation.jsm:297:19
TypeError: window.whereToOpenLink is not a function[Learn More]  ContentClick.jsm:80:17
Fetching bookmarks Object { type: "nextcloud", url: "https://mynexcloud", username: "myusername", password: "mypassword", serverRoot: "", syncing: true, localRoot: "2-iQ1Vbw0YI0", error: null, lastSync: 1529352293635 }  Nextcloud.js:141:4
No matching message handler for the given recipient. MessageChannel.jsm:912
Received bookmarks from server Array [  ]  Nextcloud.js:190:4
Successfully ended sync process for account myusername@https://mynextcloud  Account.js:174:6
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More]  notifications
No matching message handler for the given recipient. MessageChannel.jsm:912
```
I have a load of tabs open mind you so and there's a little baground activity, which on the console is only this message ever few seconds:

`No matching message handler for the given recipient. MessageChannel.jsm:912`

so not sure that relates to floccus. Of course I can't read this diagnostic with experienced eyes, but the Array [ ] is  not surprising as there are no bookmarks to receive from nextcloud, but the next line indicating Success is suspicious as I would like before then to see it send an array to Nextcloud. And of course the untrustworthy site connection is odd and suspiscious as the certs are fine.  Here is the server I'm using:

https://tinyurl.com/ya4fextb

Regards,

I haven't tried with Chrome. Will do that next.

**Comment by bernd-wechner** [comment] 2018-06-18 20:38
Just tried Chrome. Same problem, but slightly more informative debug log I think:

```
Starting sync process for account myusername@https://mynextcloud
Account.js:120 Apparently not initialized, because: Error: Invocation of form bookmarks.getSubTree(undefined, function) doesn't match definition bookmarks.getSubTree(string id, function callback)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at Object.<anonymous> (extensions::binding:363:30)
    at chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/lib/chrome-promise.js:58:14
    at new Promise (<anonymous>)
    at Object.getSubTree (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/lib/chrome-promise.js:46:16)
    at Account._callee8$ (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/background-script.js:4899:55)
    at tryCatch (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6900:40)
    at Generator.invoke [as _invoke] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:7138:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6952:21)
    at step (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/background-script.js:4542:191)
Account.js:95 initializing account 3890652384
2Account.js:120 Apparently not initialized, because: Error: Invocation of form bookmarks.getSubTree(undefined, function) doesn't match definition bookmarks.getSubTree(string id, function callback)
    at Object.normalizeArgumentsAndValidate (extensions::schemaUtils:115:11)
    at Object.<anonymous> (extensions::binding:363:30)
    at chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/lib/chrome-promise.js:58:14
    at new Promise (<anonymous>)
    at Object.getSubTree (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/lib/chrome-promise.js:46:16)
    at Account._callee8$ (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/background-script.js:4899:55)
    at tryCatch (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6900:40)
    at Generator.invoke [as _invoke] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:7138:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/polyfill.js:6952:21)
    at step (chrome-extension://fnaicdffflnofjppbagibeoednhnbjhg/dist/js/background-script.js:4542:191)
Nextcloud.js:141 Fetching bookmarks Object
Nextcloud.js:190 Received bookmarks from server Array(0)
Account.js:174 Successfully ended sync process for account myusername@https://mynextcloud
Account.js:128 Starting sync process for account myusername@https://mynextcloud
Nextcloud.js:141 Fetching bookmarks {error: null, lastSync: 1529353973289, localRoot: "19942", password: "mypassword", serverRoot: "", …}error: nulllastSync: 1529353973289localRoot: "19942"password: "mypassword"serverRoot: ""syncing: truetype: "nextcloud"url: "https://mynextcloud"username: "myusername"__proto__: Object
Nextcloud.js:190 Received bookmarks from server []
Account.js:174 Successfully ended sync process for account myusername@https://mynextcloud
```

But same issue as above, seemingly received nothing from NextCloud (fine as expected) then reports success but no apparent effort to push bookmarks to NextCloud.

**Comment by marcelklehr** [comment] 2018-06-18 20:58
Which folder did you select in the account options? It's probably a newly created one, as floccus by default tries not to destroy your bookmarks ;)

**Comment by bernd-wechner** [comment] 2018-06-18 21:31
I didn't select one in either case. I presume you're asking about the Sync Folder exposed when I click the Options button? I've never entered anything there.

When I look at it now in Firefox though it read something:

![image](https://user-images.githubusercontent.com/7296506/41563150-28dff878-7392-11e8-840c-1645ab16fe5e.png)

Though I never entered anything.

If I click Choose Folder there I get a popup with no way to close it:

![image](https://user-images.githubusercontent.com/7296506/41563204-5519b29e-7392-11e8-8813-21d5c71c43eb.png)

If I click Reset then the box contains *newly created*. If I then click Sync now, the web page jumps to the Get Addons tab on the extensions page for some odd reason but if I navigate back to floccus page, I see it reports a successful sync and the Sync Folder again reads some value as in the image above.

**Comment by bernd-wechner** [comment] 2018-06-19 00:40
Alas no change :-(. 

Yes, a button or some UI clarity around that popup would be useful ;-).

Here is my config now:

![image](https://user-images.githubusercontent.com/7296506/41568980-63dfa652-73ac-11e8-92a8-bfddf0ae9e46.png)

And here is the FF debug trace of a sync:

```
Starting sync process for account myusername@https://mynextcloud  Account.js:128:6
Fetching bookmarks Object { type: "nextcloud", url: "https://mynextcloud", username: "myusername", password: "mypassword", serverRoot: "/BrowserToolbar", syncing: true, localRoot: "toolbar_____", error: null, lastSync: 1529368163401 }  Nextcloud.js:141:4
Received bookmarks from server Array [  ]  Nextcloud.js:190:4
Successfully ended sync process for account myusername@https://mynextcloud  Account.js:174:6
No matching message handler for the given recipient. MessageChannel.jsm:912
	_handleMessage/</< resource://gre/modules/MessageChannel.jsm:912:11
TypeError: e.data.substr is not a function  post2.html:11:16
	post https://duckduckgo.com/post2.html:11:16
Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored.[Learn More]
```

And still on Nextcloud I see no bookmarks.

**Comment by bernd-wechner** [comment] 2018-06-20 01:29
I have since added Adminer to my NextCloud server to look at the database directly. And can confirm there is no data in the bookmarks tables there ;-). No surprise. For some reason floccus is simply not sending bookmarks to the server yet reports success on all its tests. Odd.

**Comment by marcelklehr** [comment] 2018-06-20 01:31
Could you try it without the server path, too. Just to be sure?

**Comment by bernd-wechner** [comment] 2018-06-20 02:02
No problem. Just tried again removing the server path. No change alas. I click Sync now and it reports success but nothing appears in NextCloud. Wondering if perhaps I should clone the repo and try and get my head around how it works. I could use some upskilling, alas a bit low on time. Looks like a little more instrumentation (debug output on the console) might help. Something is failing but failing silently and in a place not tested (as the tests all pass as per images above in the original post).

**Comment by bernd-wechner** [comment] 2018-06-22 03:04
OK, tried that and it works. I now see bookmarks on nextcloud with the floccus: prefix. 

Alas that is both encouraging and concerning. Because it poses two possible paths forward and I suspect and suggest perhaps we consider both at the same time:

1) I build this new profile up step by step to the same as the old (I mean I have a load of plugins to add basically and ideally a tab session). testing at each step a sync with a new bookmark to see if it appears. If at any point it stops working We have some info. Problem with this approach is I may get all the way back to a useable profile and we have learned nothing - that is, there is something in the old profile that is interfering that we can't identify easily. And that bugs me with regards to flocuss stability into the future as this is a costly process for us both already so I'd be happy to help out producing from it not just a workaround but learning ... and a possible lasting fix so it happens to no-one else.

2) You add some more debugging code, perhaps with an extra flag (advanced debugging) in which you dump to the console more info. I can imagine for example dumping the exact messages sent to the nextcloud server, the decision points on the way and the messages received back from it). A deep drill down in a sense. That will help us find the actual problem and improve lasting quality and stability of floccus. Do you agree?

**Comment by marcelklehr** [comment] 2018-06-22 15:08
> OK, tried that and it works.

Interesting. both #\1 and #\2 sound good to me. I'll send you an alpha version of floccus v3, though, as we've been rewriting some parts, so you can test the latest code.

> Your report is similar to #123, though. Can you replicate the observation that the floccus-created folder does work for syncing?

Can you confirm this, too? In that case we can merge the two issues.

**Comment by marcelklehr** [comment] 2018-06-22 18:41
@bernd-wechner you can try [this alpha version](https://github.com/marcelklehr/floccus/releases/tag/v3.0.0-alpha-1) by going to `about:debugging`, enabling debugging and loading the xpi file as a temporary addon. Make sure to uninstall the official floccus version first or at least to delete the account, to make sure they don't interfere. ;)

**Comment by bernd-wechner** [comment] 2018-06-24 12:47
Mracel, been busy this weekend with a big event,. but just got around to trying this. Uninstalled Floccus from Firefox, ensured add-on debugging was enabled then tried to install the xpi you pointed to, but alas Firefox won't install it, complaining as follows:

![image](https://user-images.githubusercontent.com/7296506/41819152-cc0a7b84-77fe-11e8-8c2f-4af28055489a.png)

I certainly have debugging on:

![image](https://user-images.githubusercontent.com/7296506/41819164-eca368a6-77fe-11e8-9fa8-ac5be1e323d6.png)

So I saw that Load Temporary Add-on button, downloaded the xpi file and clicked that button to load it and that worked. Cool. Entered by Nextcloud details and it failed to sync

But it fails to sync:

![image](https://user-images.githubusercontent.com/7296506/41819209-b8a994de-77ff-11e8-8a5c-cd1aa8569721.png)

Yet still, passes all tests when they are run:

![image](https://user-images.githubusercontent.com/7296506/41819195-73ca70f4-77ff-11e8-889f-cd2755b4ea90.png)

So I opened the debugging consoled and tried a sync and voila, we have more clues:

```
Starting sync process for account myusername@https://mynextcloud.server  Account.js:123:6
Fetching bookmarks Object { type: "nextcloud", url: "https://mynextcloud.server", username: "myusername", password: "mypassword", serverRoot: "/BookmarksMenu", syncing: true, localRoot: "menu________", error: null, lastSync: 1529844130105 }  Nextcloud.js:173:4
Unhandled promise rejection TypeError: can't access dead object
Stack trace:
_callee9$/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21946:26
_callee9$@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21945:17
tryCatch@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:6900:37
invoke@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:7138:22
defineIteratorMethods/</prototype[method]@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:6952:16
step@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21452:183
step/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21452:361
run@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:4295:22
notify/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:4308:30
flush@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:1398:9
  polyfill.js:4326:11
Blocked loading mixed active content “http://fonts.gstatic.com/s/opensans/v15/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2”[Learn More]  game-icons.net
Blocked loading mixed active content “http://fonts.gstatic.com/s/opensans/v15/mem8YaGs126MiZpBA-UFVZ0b.woff2”[Learn More]  game-icons.net
Received bookmarks from server Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, 306 more… ]  Nextcloud.js:239:4
COMPARE Object { localItem: Object, cacheItem: Object, serverItem: Object }  SyncProcess.js:36:4
Checking subtree of  Object { localItem: Object, serverItem: Object }  SyncProcess.js:204:4
Successfully ended sync process for account myusername@https://mynextcloud.server  Account.js:161:6
Unhandled promise rejection TypeError: can't access dead object
Stack trace:
_callee9$/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21946:26
_callee9$@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21945:17
tryCatch@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:6900:37
invoke@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:7138:22
defineIteratorMethods/</prototype[method]@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:6952:16
step@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21452:183
step/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/background-script.js:21452:361
run@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:4295:22
notify/<@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:4308:30
flush@moz-extension://b333d6af-00bf-46c3-8235-68a8e585e72b/dist/js/polyfill.js:1398:9
  polyfill.js:4326:11
```

I'm sure you can read that better than I but I see:

Unhandled promise rejection TypeError: can't access dead object

and a stack trace that might help! I call that progress.

**Comment by bernd-wechner** [comment] 2018-06-25 02:04
Hold our horses. I was tired last night  and stopped at the reported error message in the UI and console. But this morning I checked my NextCloud instance and see that the bookmarks are there. I haven't checked them exhaustively but there are a load, and they look ;like mine ;-). 

No thrill by the NextCloud Bookmarks UI and the need to use tags to mimic the hierarchy, but in the end it's not a huge issue clearly as that's just the store and the goal is to get them replicated on browsers.  Still, nice to image on day the NextCloud Bookmarks app implements a tree-based organisation system ...

In the mean time it looks like the alpha does upload the bookmarks but dies on an error nonetheless, that needs diagnosing.

**Comment by marcelklehr** [comment] 2018-06-25 18:15
Mh. It's highly unlikely, that floccus created bookmarks without logging something about it in the console. I suspect the bookmarks on the server were still there from syncing with your new profile? I need to debug those dead object errors myself, but `Successfully ended sync process` means the sync process was successful and flawless without errors. I suspect the dead object errors are from trying to update the options UI, the handle to which seems to die mid-way through.

The UI will get better soon-ish, btw (heh, I've been saying that for a few months now :see_no_evil:)

**Comment by bernd-wechner** [comment] 2018-06-26 02:03
The new profile has none of those bookmarks so they can only have come from the old profile alas.  It's quite a hassle to change profiles and use FF a lot so I've not got around to trying it again, but the new profile has only the default bookmarks and my old profile (which was managed by Xmarks)  has hundreds of bookmarks well sorted into a hierarchy of interests that I'm used to seeing on all my instances of Firefox and Chrome (thanks to Xmarks which is no more). They are all froze now at the state they were when Xmarks was killed off.  But it's easy for me to see the difference between the new test profiles handful of bookmarks and my customary huge list of them. What I can't easily see is if it's complete in Nextcloud, and I haven't tries synching Chrome to to yet either alas as I've been busy as, and ill. But that's a next step too. 

Alas the UI is showing this error which pout me on hold and this diagnostic path. Still if ever I find/make time I will look at cloning and examining code myself too, but alas I am busy and the interest lies in the very fact that I have zero experience with Mozilla add-ons so far and am happy to upskill a bit plus of course help out on a cool project like this.

**Comment by marcelklehr** [comment] 2018-07-16 20:44
The new beta version should work more stable. I'm closing this for now, since it appears to be fixed in the upcoming version.

**Closed by marcelklehr** 2018-07-16 20:44 UTC
Labels: bug, waiting for more information
