### ISSUE TITLE
Floccus lock files create email spam

### ISSUE THREAD

**Issue by Jolopu** [marcelklehr/floccus#685] opened 2020-10-18 19:49 UTC
The latest Floccus release keeps creating and deleting lock files on Nextcloud server leading to ongoing annoying server messages.
<img width="774" alt="floccus-lock" src="https://user-images.githubusercontent.com/34797349/96378345-9bfb5c00-118b-11eb-8e64-ebeaf60117d1.png">

**Comment by marcelklehr** [comment] 2020-10-19 13:57
Thanks for the feedback! I'll  fix this with the next release.

**Comment by armadillo11** [comment] 2020-10-29 09:28
Hi Marcel, what do you mean by next release? In the meantime there were several updates with small fixes... These email notifications are really annoying... Regards, Stefan

**Comment by marcelklehr** [comment] 2020-10-29 12:15
> what do you mean by next release?

Yep, I did mean the next release, but shit hit the fan and I had to focus on more pressing issues first. Sorry.

**Comment by Jolopu** [comment] 2020-10-29 12:16
I'm also using Brave browser which is technically a Chromium browser. The latest Floccus version there is 4.3.0. So I don't have this issue there. But I guess when the update to 4.4.+ comes the issue will be back unless Marcel solves it in the meantime. ;-)

**Comment by marcelklehr** [comment] 2020-10-29 19:15
So, it's not as easy as I thought to fix this, because nextcloud doesn't provide a default file locking mechanism and the files_lock app is very broken. I'm happy to change the file creation/deletion into a simple file write mechanism, but I suppose this will just give you a different notification message that the file was changed. Floccus needs locking to avoid other issues, though. I'm open for suggestions, but for now I think there's no easy fix for this beyond turning off notifications.

**Comment by Jolopu** [comment] 2020-10-29 19:41
Notifications of file changes/creation/deletion are crucial for collaborative work. As I said I use Floccus 4.3.0 with Brave/Chrome. Everything works flawlessly without any unwanted notifications. Why change a running system?

**Comment by armadillo11** [comment] 2020-10-29 19:53
Well, locks are a must if you work asynchronously and/or in a concurrent protocol. Therefore I understand the need for locking. What about using the underlying nextcloud database for locking? Just an idea, I don't know the internals of nextcloud at all...

Regards, Stefan

**Comment by Jolopu** [comment] 2020-10-30 10:53
I know there is a cron lock in Nextcloud. Another idea would be to save the lock file not into the data folder but instead into a different folder that is outside the scope of the notification function. Just my thoughts. I'm not a programmer.

**Comment by simmstein** [comment] 2020-11-01 16:37
In addition to this problem of notification, the floccus api access must not have permission to write a file! You should use the database instead of a file for your lock mechanim.

**Comment by ItsOnlyBinary** [comment] 2020-11-02 16:38
I've have just hit another issue related to this one.

My nextcloud trash is filled with >7900 hidden `.floccus-[some_hash_looking_string].lock` files. MySQL is not happy with me trying to delete them all.

Does sound like storing the lock info in the database would be the way to go.

**Comment by chainria** [comment] 2020-11-02 16:51
I had to disable the addon for now, some problem as https://github.com/marcelklehr/floccus/issues/685#issuecomment-720584850 I had 6000+ files in my trash which completely broke it for me. Had to delete them via WebDAV, actually still waiting for it to go through.

**Comment by marcelklehr** [comment] 2020-11-03 20:14
> My nextcloud trash is filled with >7900 hidden .floccus-[some_hash_looking_string].lock files.

Ooof, I didn't see this coming. It seems that the locking functionality as it is implemented now was a bad idea, I'll remove it with the next patch.

**Comment by rakekniven** [comment] 2020-11-04 07:54
Same here, have two devices syncing and activity log is flooted with locking files.

Using v3.4.7

**Comment by chainria** [comment] 2020-11-04 08:07
This really needs to 

> > My nextcloud trash is filled with >7900 hidden .floccus-[some_hash_looking_string].lock files.
> 
> Ooof, I didn't see this coming.
> 
> It seems that the locking functionality as it is implemented now was a bad idea, I'll remove it with the next patch.

Thank you very much. it pretty much crippled my NC instance, I had to resort to taking it offline and deleting over 8000 files from the trashbin as well as activity, files, files_trash and filecache tables. Then everything went back to normal thankfully.

Would you please kindly signal when 4.4.6 (or whatever version includes the fix) is released? So I can re-enable and test again.

**Comment by marcelklehr** [comment] 2020-11-04 14:12
4.4.6 is available now.

**Comment by simmstein** [comment] 2020-11-04 14:30
What about NC 19 users?

**Comment by rakekniven** [comment] 2020-11-04 14:32
> 4.4.6 is available now.

Works for me.

**Comment by rakekniven** [comment] 2020-11-04 14:32
> 
> 
> What about NC 19 users?

The issue is related to firefox add-on?

**Comment by chainria** [comment] 2020-11-04 16:46
> 4.4.6 is available now.

Works like a charm for me, synced within seconds, no dreaded lock files.

**Comment by simmstein** [comment] 2020-11-04 16:58
Thanks!

**Closed** 2020-11-04 18:21 UTC
Labels: bug

**Comment by cpunk** [comment] 2021-02-16 00:26
does not seem to work in owncloud 10.6 with floccus 4.5: every sync operation produces an entry in the recycle bin.

**Comment by marcelklehr** [comment] 2021-02-16 12:42
@cpunk Yes, the WebDAV method still uses lock files.
