### ISSUE TITLE
Support bookmarks without title

### ISSUE THREAD

**Issue by simonspa** [marcelklehr/floccus#137] opened 2018-07-30 06:05 UTC
In my Firefox bookmakr toolbar I have many bookmarks without title. I add bookmarks to the bar and then remove the title completely son that only the icon is left - in many cases enough information for me to distinguish the different entries. However, floccus doesn't seem to play nicely with this:

### Software versions

* Browser: Firefox 61.0.1
* Nextcloud: 13.0.5
* Nextcloud Bookmarks app: 0.11
* Floccus: 2.2.8

### Steps to reproduce
1. Create a boomark e.g. in the bookmarks toolbar
2. Remove its title, so only the icon is left
3. Wait for a sync

### Expected outcome
The bookmarks are synched as they are supposed to, without changes to the bookmark itself

### Actual outcome
The page title is set as bookmark title by floccus, and the bookmark is moved to the end of the list (or toolbar)

**Comment by marcelklehr** [comment] 2018-07-30 12:04
Thanks for reporting! This is a known issue. Thus I'm closing it as a duplicate of #132 ;)

**Closed by marcelklehr** 2018-07-30 12:04 UTC
