### ISSUE TITLE
Erroneous URL encoding across synchronizations

### ISSUE THREAD

**Issue by mseitzer** [marcelklehr/floccus#191] opened 2018-11-12 18:01 UTC
### Software versions

* Browser: Firefox 63.0
* Nextcloud: 13.0.6
* Nextcloud Bookmarks app: 0.12.2
* Floccus: 3.0.10

### Steps to reproduce
1. Add URL `https://groups.google.com/forum/m/#!categories/ml-news` to bookmarks
2. Sync with server
3. Sync with server again

### Expected outcome

The URL `https://groups.google.com/forum/m/#!categories/ml-news` should be kept the same across synchronizations. 
No encoding should be applied.

### Actual outcome

The URL is now bookmarked as `https://groups.google.com/forum/m/#%21categories%2Fml-news` (visiting this URL does not result in the correct page).

**Comment by marcelklehr** [comment] 2018-11-12 18:07
Thanks for reporting this, however, it turns out that it has been reported before: This is a duplicate of #183 and is fixed in nextcloud bookmarks v0.14.0

**Closed by marcelklehr** 2018-11-12 18:07 UTC
