### ISSUE TITLE
Error: Trying to remove a non-existing ite

### ISSUE THREAD

**Issue by dilectia** [marcelklehr/floccus#643] opened 2020-08-25 07:44 UTC
**Describe the bug**
I get this error in Firefox (not in Chrome with the same config)
Trying to remove a non-existing item from OrderTracker: folder:toolbar_____

**To Reproduce**
I just let flocus run... and get the error from the plugin icon

**Expected behavior**
Sync without errors XD

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu Linux 18.04 LTS
 - Browser Firefox
 - Browser Version 79.0 (64-bit)
 - Floccus version: 4.3.0
 - Floccus sync method:  nextcloud folders

**Server (please complete the following information):**
 - Ubuntu core 18.04
 - Nextcloud version: 19.0.1
 - Bookmarks app version: 3.3.3

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
If you think it's relevant I'll provide it

- [ ] Debug log provided

**Additional context**
I sync bookmarks with my toolbar bookmarks in firefox and chrome. I only get this error in Firefox...

**Comment by brainchild0** [comment] 2020-08-25 10:31
Also affected, using same browser configuration and extension version, under  Linux Mint 20.0.

---

```
Trying to insert an already existing item into OrderTracker: bookmark:ORVCoXSse5Zk
```

**Comment by marcelklehr** [comment] 2020-08-25 19:41
> I get this error in Firefox (not in Chrome with the same config)

That's curious. 

> I had hoped that update would resolve it.

So had I :/

I'll look into this.

**Comment by sleepinghua** [comment] 2020-08-30 00:23
Same problem:

**"Trying to remove a non-existing item from OrderTracker: bookmark:1820\nTrying to remove a non-existing item from OrderTracker: folder:2219"**

- windows 19041.450
- chrome 85.0.4183.83 x64
- Floccus version: 4.3.0
- Floccus sync method: WebDAV

**Comment by marcelklehr** [comment] 2020-09-01 14:03
Good news: I've been able to [reproduce this error with fuzzy testing](https://github.com/marcelklehr/floccus/runs/1056456345). Now I just need to find the cause :)

**Comment by dilectia** [comment] 2020-09-01 17:14
It probably doesn't add any info, but suddenly it works fine... I don't think I have done anything...

**Comment by brainchild0** [comment] 2020-09-01 21:24
Following @dilectia's observation, I noticed that the upgrade from Firefox 79.0 to 80.0 appears to resolve the issue.

**Comment by brainchild0** [comment] 2020-09-01 21:26
Also, probably OT, but after the error occurred, I noticed that the extension ignored requests to restart the synchronization operation. Only restarting the entire browser would make it possible to start a new operation.

**Comment by marcelklehr** [comment] 2020-09-18 13:34
Thanks for all your feedback, folks! I'm currently working on a new iteration of the sync algorithm that should fix this: #651

**Comment by marcelklehr** [comment] 2020-10-05 15:51
I've since rewritten the sync algorithm to avoid this kind of problems. Head over to https://github.com/marcelklehr/floccus/issues/666 if you'd like to help test the new version.

**Comment by marcelklehr** [comment] 2020-10-12 13:21
I'd be very grateful if you could try out the release candidate: #666 -- I promise, you'll get extra cookies :) :heart:

**Comment by brainchild0** [comment] 2020-10-12 13:23
The problem, at least for me, is that such a test would have no value, unless under the earlier version of Firefox, because the problem resolved in recent versions. (See previous comment.)

**Comment by marcelklehr** [comment] 2020-10-12 13:33
I see. Since OP hasn't responded in a while I'm gonna close this. Please shout if you do continue to experience this :)

**Closed by marcelklehr** 2020-10-12 13:33 UTC
Labels: bug
