### ISSUE TITLE
Floccus hangs browser if accessing Owncloud with 200+ bookmarks

### ISSUE THREAD

**Issue by e-alfred** [marcelklehr/floccus#6] opened 2016-12-12 14:03 UTC
Hello,

I am having problems with floccus 1.1.2 running on Firefox 50.0.2 on Debian 8 while accessing my bookmarks on Owncloud 9.1 running the bookmarks app 0.9.0. If I try to save a bookmark or open the Owncloud folder in my Firefox bookmarks, it hangs pretty often telling me if I want to debug/stop/continue this script:

 `Script: chrome://browser/content/places/browserPlacesViews.js:276`

Also the browser is generally unresponsive as long as the floccus addon is activated.

**Comment by marcelklehr** [comment] 2016-12-12 16:21
Hi @e-alfred!
Thank you for letting me know. Could you access `about:debuging`, debug floccus and paste some of the messages here (anonymized, of course)?
My setup seems to have other problems at the moment, so I haven't tried to replicate, yet.

**Comment by marcelklehr** [comment] 2016-12-15 19:56
It seems, that floccus doesn't work with the latest version of Bookmarks, yet. I'll update it, though.

**Comment by marcelklehr** [comment] 2016-12-16 16:32
I think I know what the problem is, and the solution is something I should have done a while ago: https://github.com/nextcloud/bookmarks/pull/322 ;)

**Comment by marcelklehr** [comment] 2017-05-16 21:26
I'm closing this as the new release shouldn't have this problem. Let me know if this happens in the latest version as well.

**Closed by marcelklehr** 2017-05-16 21:26 UTC

**Comment by dkadioglu** [comment] 2019-10-21 12:48
I am using Floccus 3.5.1 in combination with Nextcloud 17 and Bookmarks 2.2.0. I have 5198 bookmarks at the moment and still have the problem, that Firefox hangs during syncs. Do you need any further information?
