### ISSUE TITLE
bookmark sync never ends and canť be interrupted

### ISSUE THREAD

**Issue by ratermir** [marcelklehr/floccus#383] opened 2019-10-01 15:52 UTC
In my bookmark set, when synchronitation starts and continues up to approx. 60%, then it stops and never continue again. When I press the "Cancel sync" button, nothing happens. 

Browser log ends with message "This bookmark was moved here" - no further message. 
![image](https://user-images.githubusercontent.com/52619304/65959152-8cf71e00-e451-11e9-8648-4f735892b11e.png)

I've captured logs and messages. I am attaching captured data here. Note that duplicities (stored on the server) are increased after some changes and synces in client. Since I still manipulate with bookmarks, I cant tell which changes on client cases them.
[bookmarks_messages.zip](https://github.com/marcelklehr/floccus/files/3677310/bookmarks_messages.zip)

This data could also be useful for issue #383

**Comment by marcelklehr** [comment] 2019-10-10 10:48
Is this with the overwrite sync strategy?

**Comment by ratermir** [comment] 2019-10-10 13:58
No, the strategy is "Merge".

**Comment by ratermir** [comment] 2019-10-10 15:42
Just now, when I unchecked "parallel" syncing, the synchronization finished normally. 
I have posted several bugs here (as the behaviour developed in time)
Then I checked parallel sync again and started synchronization, it ended with success. So the behaviour is a little strange. 
So I will observe it for some time 'let say 4 days), if the issue dows not repeat, we can close this issue (and also #374 )

**Comment by ratermir** [comment] 2019-10-11 15:06
I repeated 3 times and I confirm, this behaviour occures only if parallel syncing is enabled. 
In case "Speed up synchronization" is unchecked, everything works well. 

I captured one more log - if it is useful for your analysis. 
[fnaicdffflnofjppbagibeoednhnbjhg-1570801028181.zip](https://github.com/marcelklehr/floccus/files/3718255/fnaicdffflnofjppbagibeoednhnbjhg-1570801028181.zip)

**Comment by gerroon** [comment] 2019-10-23 23:23
I have this issue once in a while but also during the sysncing, I cnanot access any websites whatsoever, I have to either wait for the sync to end to be able to visit sites, and if the sysnc is stuck the only way to get sites visiting work is to restart the browser.

**Comment by bhlevca** [comment] 2019-10-24 01:01
Occasionally, I experience the same thing, more often lately.  Sometimes I find that the lock file management is faulty, especially if multiple browsers compete. Sometimes I need to set Trigger sync from star, which is not always what I want to do. The later tends to create duplicate directories in my bookmark tree. What I describe is probably multiple bugs in one.

**Comment by dkadioglu** [comment] 2019-11-12 10:38
I have the same problem: during sync I cannot visit websites as the whole browser hangs. In my case this is during every single sync and doesn't depend on whether Speed up Sync is enabled or not. Also see https://github.com/marcelklehr/floccus/issues/6#issuecomment-544498709. Due to this I set the sync interval quite high - as far as I can see, there is no possibility to disable the automatic sync, right?
@bhlevca One question: What and where is the setting Trigger sync from star?

**Comment by marcelklehr** [comment] 2019-11-12 22:04
> What and where is the setting Trigger sync from star?

It's called `Trigger sync from scratch` ;)

**Comment by marcelklehr** [comment] 2019-11-12 22:09
> What I describe is probably multiple bugs in one.

This. :smile: 

This issue is for sync getting stuck. I appreciate feedback and will look into it, but *please* keep things ordered and file a new issue :sweat_smile: That would be one for *I cnanot access any websites whatsoever*, and one for *Sometimes I find that the lock file management is faulty, especially if multiple browsers compete* and one for *The later tends to create duplicate directories in my bookmark tree* :pray: :relaxed:

**Comment by bhlevca** [comment] 2019-12-06 04:40
I have the same problem but only on Firefox. On Chrome it works OK,. In general the firefox version sucks while the chrome version is good.  On Chrome cancel Sync works while on Firefox does not. 
On Chrome the sync finishes while on firefox doesn't. When people file a bug they should specify on which browser. Also, bookmarks duplication also seems to happen only on firefox, but I am not 100% sure on the last one.  If you want me to file a bug report for each issue form above please let me know

**Comment by marcelklehr** [comment] 2019-12-06 14:19
Feel free to open new issues. If in doubt file a new one :) Also, duplication on firefox may be due to nativ bookmarks sync interfering with floccus (which is why it should be disabled).

**Comment by bhlevca** [comment] 2019-12-06 15:50
It is possible that I have other sync enabled. I will check and disable if it is enabled. Still, the firefox version has sync problems that I don't have on the chrome version.

**Comment by marcelklehr** [comment] 2019-12-06 16:25
Yes, overall performance on firefox is much worse than on chrome, sadly, the code is the same, though, so this is in large part due to firefox :/ I hope things will improve as the firefox team refactors their code base, though.

**Comment by bhlevca** [comment] 2019-12-06 16:52
Still, Eversync seems to work equally well on both. How are they doing it? Perhaps there are differences in the bookmark API?

**Comment by bhlevca** [comment] 2019-12-06 16:53
What I hat the most is that you cannot cancel the sync, which I think it is not Firefoxes' problem

**Comment by marcelklehr** [comment] 2019-12-06 17:03
> What I hate the most is that you cannot cancel the sync, which I think it is not Firefoxes' problem

That's probably true, I'll see what I can do about this.

**Comment by marcelklehr** [comment] 2019-12-10 19:31
I've published a new patch release which might fix this (personal confidence level 13%). If you could retry with the new version and report back, I'd be grateful :)

**Comment by bhlevca** [comment] 2019-12-10 20:07
> I've published a new patch release which might fix this (personal confidence level 13%)

I tested it. Confidence level went to 0% :-(  All it does is unchecking the enabled check-mark but does not cancel it.

**Comment by marcelklehr** [comment] 2019-12-10 23:58
mh. We could try to raise the confidence level in case you are willing to provide an export of your bookmarks confidentially (via email, or other transport of your choice).

**Comment by bhlevca** [comment] 2019-12-18 15:37
Sorry, I was away.  However, I don't think that you need my bookmarks to see that clicking on the "Cancel sync" button just unchecks the "Enable check mark instead of stopping the synchronization.

**Comment by bhlevca** [comment] 2019-12-18 15:38
By the way, the latest change screwed up the chrome plugin too, which has similar behaviour as described above. It should be easy to check with any bookmarks

**Comment by marcelklehr** [comment] 2019-12-18 16:46
I understand, I have indeed tried to replicate this, however, and have not succeeded. With the datasets I've tried it admittedly took a little while (due to the way the feature is implemented), but eventually the sync was canceled.

**Comment by bhlevca** [comment] 2019-12-18 17:20
Could it be that the synchronization just finished instead?
What bugs me the most is the fact that it unchecks the "enabled" button. Why is it necessary to disable, when the action is just to cancel?

**Comment by bhlevca** [comment] 2019-12-18 17:21
I figured, if you press cancel immediately after you press sync you will reproduce the behaviour I told you about.

**Comment by bhlevca** [comment] 2019-12-18 17:22
I suppose that it is a thread mishandling issue, mutex, etc.

**Comment by marcelklehr** [comment] 2020-03-02 13:32
The deadlock is resolved in the newly released v4.0.0. Thanks for your patience

**Closed by marcelklehr** 2020-03-02 13:32 UTC
Labels: bug
