### ISSUE TITLE
Export/Import function

### ISSUE THREAD

**Issue by DerDanilo** [marcelklehr/floccus#575] opened 2020-06-18 11:47 UTC
**Is your feature request related to a problem? Please describe.**
I run multiple browser on multiple devices, syncing multiple different folder with multiple different teams and it takes quiet some time to setup floccus on all of them without messing up a setting or syncing the wrong folder. Or any of the team members could just mess up.

**Describe the solution you'd like**
Add an export and import function that also allows (optional) to safe the passwords encrypted by providing a password to decrypt the settings file while importing.
It would be helpful to make the settings file editable so that one can change settings in the file before sending it to someone else. 

**Describe alternatives you've considered**
Workarround: Setup every browser and every sync manually on every device. Extremely time consuming. 

**Additional context**
-

Thanks!

**Comment by marcelklehr** [comment] 2020-06-18 12:37
This is a duplicate of #422 :)

**Closed by marcelklehr** 2020-06-18 12:37 UTC
Labels: enhancement

**Comment by DerDanilo** [comment] 2020-06-18 12:39
But this description is what you asked for, the other request is just something like "not working" :)

**Comment by marcelklehr** [comment] 2020-06-18 12:48
> But this description is what you asked for

I did? #422 is indeed a little poorly documented, but it's on my list :) I'll add your description to that issue :)
