### ISSUE TITLE
XBEL not picking up new folders

### ISSUE THREAD

**Issue by xelcho** [marcelklehr/floccus#347] opened 2019-08-08 11:58 UTC
### Software versions
OS: ubuntu 18.04 lts
- Browser: firefox quantum
- Nextcloud: 14
- Nextcloud Bookmarks app: 1.1.1
- Floccus: 3.3.2
- Floccus sync method:  XBEL/webdav
  

### Steps to reproduce

1. added new folder to root of bookmarks toolbar with bookmarks in it.
2.

### Expected outcome

after multiple syncs, expected it to show up on other synced machines.
...

### Actual outcome

after multiple syncs, expected it did not show up on other synced machines.
...

### Debug log

- [ ] Debug log provided

**Comment by marcelklehr** [comment] 2019-08-10 21:54
Mh. I cannot reproduce this. Does the folder end up in the xbel file?

**Comment by xelcho** [comment] 2019-08-15 15:48
Sorry for the delay!

I am not able to find the folder in the xbel file.

**Comment by marcelklehr** [comment] 2019-08-19 12:25
Which folder did you select to be synced?

**Comment by xelcho** [comment] 2019-08-19 14:10
I added a new folder to Firefox (on client machine) and expected it to be picked up by floccus and replicated to other client machines. This has been the pattern that has worked in the past, and I don't recall changing anything in the mean time.

Does that answer your question?

**Comment by marcelklehr** [comment] 2019-08-19 14:12
Did you try syncing manually?

**Comment by xelcho** [comment] 2019-08-19 14:20
For my understanding: Manually Sync is clicking on "Sync now" button in the extension?

I will give the beta a try.

**Comment by marcelklehr** [comment] 2019-08-19 14:38
> For my understanding: Manually Sync is clicking on "Sync now" button in the extension?

Yes. But I assume you tried that already.

**Comment by xelcho** [comment] 2019-08-19 14:41
> Yes. But I assume you tried that already.
You know, I think so. Let's table this until I am home and can do so for certain!

Thanks!

**Comment by xelcho** [comment] 2019-08-21 20:48
It seems that the client is hanging on sync, regardless if it is automatic or manually initiated. It gets hung at...
![Screenshot_20190821_163640](https://user-images.githubusercontent.com/30007489/63466992-71502f00-c432-11e9-9a85-4b90020362e3.png)
If I "mess" with it, I get issues with file locking.
If I delete the lock file, it hangs at the same spot.
I am not sure what I should be looking for in the debug log on client, the following are the last 2 lines:

Syncing failed with E023: Unable to clear lock file, consider deleting bm/bookmarks.xbel.lock manually.
onSyncFail

**Comment by marcelklehr** [comment] 2019-08-21 22:04
Can you check the debug log, when it hangs?

**Comment by xelcho** [comment] 2019-08-22 10:32
Client debug log:

> I am not sure what I should be looking for in the debug log on client, the following are the last 2 lines:

>Syncing failed with E023: Unable to clear lock file, consider deleting bm/bookmarks.xbel.lock manually.
>onSyncFail

It is working, for now, by renaming the xbel file and creating a new one. Let's see if the other clients behave. :)

**Comment by bhlevca** [comment] 2019-08-22 13:28
I am experiencing periodically the same behaviour and I need quite often to
delete the lock file and sometimes the xbel file.  There is something
corrupting the process and I think that the locking mechanism need to be
reviewed. In particular, if a sync process is stopped for various reasons
including closing the browser, the lock file is not removed. Also,it
happens one in a while that I get duplicates, sometimes folders sometimes
duplicates inside the folder. It is so random that it is hard if not
impossible to catch.

I don't know how can I help  to fix these issues.

Bogdan
ᐧ

**Comment by xelcho** [comment] 2019-08-22 13:40
So on my windows 10 firefox quantum client, the sync can not complete the debug log:

Bookmark unchanged
Syncing failed with E011: Item in folder ordering is not an actual child: {"id":813,"type":"bookmark"}
E011: Item in folder ordering is not an actual child: {"id":1353,"type":"bookmark"}
E012: Folder ordering is missing some of the folder's children
E012: Folder ordering is missing some of the folder's children
E011: Item in folder ordering is not an actual child: {"id":1333,"type":"bookmark"}
onSyncFail

Please advise, thx.

**Comment by marcelklehr** [comment] 2019-08-23 23:00
@xelcho uh,oh. These errors suggest an inconsistency occurring somewhere in the sync algorithm. Are you using the new beta for this? Did you enable a different syncing strategy?

**Comment by bhlevca** [comment] 2019-08-24 01:16
Hi,

I don't use the beta version and I get occasionally the same errors.

Bogdan

**Comment by xelcho** [comment] 2019-08-25 14:01
@marcelklehr So I am not using the beta, same version from start of this post (3.3.2)

Current situation:
Home Client (Ubuntu) works fine, I can add bookmarks and folders and it syncs as it should. 
My work Client (Windoz 10) with firefox is the machine having fits. 

Please advise.

I'm considering download the bookmarks from my work machine, wipe them and rebuild from sync.

**Comment by marcelklehr** [comment] 2019-08-26 00:53
I've just released v3.4.0. You can now easily run the latest code.

**Comment by marcelklehr** [comment] 2019-09-02 09:27
@bhlevca Feel free to open a separate issue with your errors

**Closed by marcelklehr** 2019-09-02 09:27 UTC
