### ISSUE TITLE
Bookmarks and folders re-arranged in Alphabetical Order - WebDAV/xbel

### ISSUE THREAD

**Issue by darrellittle** [marcelklehr/floccus#150] opened 2018-08-23 21:50 UTC
### Software versions

* Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Browser: Firefox 61.0.2 (64-bit)
* Nextcloud: 13.0.5
* Nextcloud Bookmarks app: Using WebDAV/xbel
* Floccus: 3.0.1

### Steps to reproduce

1. Deleted the Nextcloud Bookmarks account in Chrome
2. Removed Floccus from chrome and re-added
3. Exported backup copy of browser bookmarks
4. Created new account using Floccus 3.0.1 and WebDAV to Nextcloud server. Set to sync Bookmarks Bar only.
5. Imported backup copy of bookmarks
6. Start Sync
7. Repeated Steps 1-4 in Firefox
8. Started Sync in Firefox with "Reset Cache" checked

### Expected/Actual outcome

I was hoping the bookmarks and folders would keep the same order as the initial synced browser's bookmarks, but everything was rearranged into alphabetical order, including bookmarks and folders in all subfolders. 

Is there a way to have the bookmarks appear in a custom order as opposed to alphabetical, and have that carry over to all browsers? By custom, I mean arrange the bookmarks in either Chrome or Firefox the way I want, and then do the initial sync using Nextcloud and WebDAV. 

Thanks

**Comment by marcelklehr** [comment] 2018-08-24 15:04
Hey there,
That's currently not implemented. It is however possible with the WebDAV/XBEL adapter.
As this has been requested before, I'm closing this as a duplicate of #113

**Closed by marcelklehr** 2018-08-24 15:04 UTC
