### ISSUE TITLE
This shouldn't happen! Please tell the developer about this!

### ISSUE THREAD

**Issue by dsiminiuk** [marcelklehr/floccus#92] opened 2018-05-02 13:38 UTC
* Browser: SRWare Iron Chrome Version 65.0.3400.0 (Official Build) (32-bit)
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app: 	0.11.0
* Floccus: 2.1.0

### Steps to reproduce

1. Installed, setup connection to NC with existing bookmarks, initial sync.
2. Exclamation Mark error appears on the Floccus icon...

✘ Error! OptionsSync now
Trying to create a URL that is already bookmarked. This shouldn't happen! Please tell the developer about this! url=http://aprs.org/D7xx/d710-setup.txt

If I can't sync bookmarks between multiple browsers then what's the point?

**Comment by marcelklehr** [comment] 2018-05-02 14:49
Hey @dsiminiuk 
Thank you for reporting this error. It's been reported over here, too: #78 (Hence, I'm closing this as a duplicate.)
The cause of this error seems to be a bug in the nextcloud bookmarks app, which will be fixed in its upcoming version.

**Closed by marcelklehr** 2018-05-02 14:49 UTC

**Comment by marcelklehr** [comment] 2018-05-10 15:39
This should be fixed in v2.2.2, let me know if you still experience the error in that version.

**Comment by marcelklehr** [comment] 2018-05-11 11:11
That's unlikely, as I've released v2.2.2 just yesterday ;)

**Comment by dsiminiuk** [comment] 2018-05-11 13:14
It looks like my extensions autoupdated 5/10/2018. I absolutely didn't install it again manually. 

Thanks
