### ISSUE TITLE
Couldn't authenticate with the server

### ISSUE THREAD

**Issue by naevtamarkus** [marcelklehr/floccus#701] opened 2020-10-22 21:36 UTC
**Describe the bug**
Hi, I'm trying this firefox plugin and am having trouble using it.
The problem is that, after I enter the connection details and I click on Sync Now, I get an "Couldn't authenticate with the server" error. The log shows:

2020-10-22T21:40:38.337Z Starting sync process for account myuser@myserver.org
2020-10-22T21:40:38.344Z onSyncStart: begin
2020-10-22T21:40:38.345Z https://myserver.org/mypath/bookmarks.xbel.lock
2020-10-22T21:40:38.359Z Syncing failed with E018: Couldn't authenticate with the server
2020-10-22T21:40:38.362Z onSyncFail

My first reaction is: there is something wrong with the server... but there's not; I can access the folder and files without trouble with other webdav browsers (and Firefox itself, after authenticating with the same credentials). I've tried multiple times to remove and reinstall the plugin, even an older version.

Thanks!

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Browser Version 81.0.2
 - Floccus version: 4.4.2
 - Floccus sync method: webdav

**Server (please complete the following information):**
 - OS: Linux
 - SabreDav 3.2

**Comment by redpop** [comment] 2020-10-23 18:30
**Describe the bug**
E018 Authentication Error with Firefox Add-On.
I haven't problems with the Chrome extension.

**Expected behavior**
Bookmarks should be synced with Firefox Add-On.

**Desktop:**
 - OS: macOS 11 Beta
 - Browser: Firefox
 - Browser Version: 82.0
 - Floccus version: 4.4.2
 - Floccus sync method: Nextcloud folders

**Server:**
 - OS: Ubuntu 20.04
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.4

**Debug log**
2020-10-23T18:26:04.197Z Starting sync process for account foo@foo.bar.de
2020-10-23T18:26:04.249Z onSyncStart: begin
2020-10-23T18:26:04.249Z https://foo.bar.de/remote.php/webdav/.floccus-L0ZhdkJhcg==.lock
2020-10-23T18:26:04.707Z Syncing failed with E018: Authentifizierung fehlgeschlagen
2020-10-23T18:26:04.709Z onSyncFail

**Comment by marcelklehr** [comment] 2020-10-23 19:24
With the new version of floccus you will need to grant it permissions to files as well.

**Comment by redpop** [comment] 2020-10-24 10:13
And where do I grant it permissions?

**Comment by marcelklehr** [comment] 2020-10-29 13:38
> With the new version of floccus you will need to grant it permissions to files as well.

This only applies if you are using Nextcloud flow to authenticate.

This seems to be the place.

![image](https://user-images.githubusercontent.com/986878/97580996-52fda000-19f4-11eb-9ab1-8b958a89d620.png)

**Comment by marcelklehr** [comment] 2020-10-29 13:38
Closing. Feel free to shout if this isn't solved.

**Closed by marcelklehr** 2020-10-29 13:38 UTC
Labels: bug
