### ISSUE TITLE
[Feature request] Backup settings

### ISSUE THREAD

**Issue by junpet** [marcelklehr/floccus#442] opened 2020-02-01 07:36 UTC
A nice Backup and Import button, so we could export/import settings easily.

**Comment by marcelklehr** [comment] 2020-02-20 21:07
This is a duplicate of #422 (Feel free to shout, if you feel that it isn't.)

**Closed by marcelklehr** 2020-02-20 21:07 UTC

**Comment by junpet** [comment] 2020-02-21 16:17
Sorry for duplicating. I only searched for the term `setting`, not the `export` nor `import`. :(

**Comment by marcelklehr** [comment] 2020-02-21 16:46
No harm done :)
