### ISSUE TITLE
Floccus loses bookmarks

### ISSUE THREAD

**Issue by asabbagh** [marcelklehr/floccus#592] opened 2020-07-06 01:38 UTC
**Describe the bug**
Floccus loses bookmarks.

**To Reproduce**
1. Create a new folder
2. Put some bookmarks inside of it
3. Wait until the Floccus sync has finished
4. Confirm folder is still there
5. Close browser (firefox) and shutdown PC
6. Some time later, start PC and check browser, bookmark folder is not there

**Expected behavior**
Bookmark folder is still there.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Browser Version 78.0.1
 - Floccus version: 4.2.5
 - Floccus sync method: nextcloud folders

**Server (please complete the following information):**
 - OS: Shared hosting, some flavour of Linux
 - Nextcloud version: 16.0.8
 - Bookmarks app version: 2.3.4

Note: Please write down the actual version numbers instead of writing 'latest'.

**Debug log**
Debug log button does nothing!

- [ ] Debug log provided

**Additional context**
Inconsistent reproduction.

**Comment by strank** [comment] 2020-07-28 19:01
Happens for me as well. Hard to reproduce cleanly, but in my case later sync seems to delete some of the bookmarks in folders. In one case, all but one.

**Comment by marcelklehr** [comment] 2020-07-28 20:06
mmh, this is weird. Are you by any chance using the browser built-in bookmarks sync as well?

**Comment by strank** [comment] 2020-07-30 23:02
No, no other sync happening.

Potentially noteworthy: I am using several browsers on several machines. Possibly running at the same time.

How does floccus deal with concurrent sync connections and/or conflicting updates? I assume new connections are delayed until previous sync finishes, and for conflicts, the newest one wins?

If that's not yet considered in the code, such race conditions could be an obvious source of this kind of issue.

**Comment by asabbagh** [comment] 2020-07-31 03:32
I am not using browser built-in bookmarks sync (or any other bookmarks sync besides floccus).

While I have multiple PCs with firefox and floccus sync setup like this, it happened even when only one browser on one PC was in use, and the others were not running.

**Comment by marcelklehr** [comment] 2020-08-01 18:25
It would be great if you could invest some time and try to find a number of steps that persistently replicate this bug :heart:

**Comment by marcelklehr** [comment] 2020-09-01 15:17
> race conditions could be an obvious source of this kind of issue.

that's a good point, the webdav adapter already has a locking mechanism, nextcloud-folders not yet.

**Comment by marcelklehr** [comment] 2020-10-05 15:51
I've since rewritten the sync algorithm to avoid this kind of problems. Head over to https://github.com/marcelklehr/floccus/issues/666 if you'd like to help test the new version.

**Comment by marcelklehr** [comment] 2020-10-12 13:19
I'd be very grateful if you could try out the release candidate: #666 -- I promise, you'll get extra cookies :) :heart:

**Comment by marcelklehr** [comment] 2021-02-04 16:43
Should be fixed now.

**Closed by marcelklehr** 2021-02-04 16:43 UTC
Labels: bug
