### ISSUE TITLE
Folder's name change not syncing

### ISSUE THREAD

**Issue by JULIANLEEEEE** [marcelklehr/floccus#296] opened 2019-05-18 04:00 UTC
### Software versions

- Browser: Chrome 74.0.3729.157 64-bit & Firefox 67.0 64-bit
- Nextcloud:
- Nextcloud Bookmarks app:
- Floccus: 3.2.16
- Floccus sync method: webdav
  

### Steps to reproduce

1. I changed the name of a bookmark folder in Chrome then launched floccus to sync.
2. After syncing done, I launched floccus on Firefox to sync.

### Expected outcome

I thought the name of this folder would change.

### Actual outcome

Although the bookmarks changes in this folder was synced correctly, the name of this folder didn't changed.

### Debug log

- [ ] Debug log provided

**Comment by marcelklehr** [comment] 2019-06-13 16:10
Just tried to reproduce with v3.3.0 and it seems to be fixed. Can you try again as well? I'm closing for now. Shout here, if you still face this problem with the latest version.

Cheers

**Closed by marcelklehr** 2019-06-13 16:10 UTC
