### ISSUE TITLE
Cannot sync bookmarks from Nextcloud to root folder in Chrome

### ISSUE THREAD

**Issue by kotliary** [marcelklehr/floccus#657] opened 2020-09-14 21:52 UTC
**Describe the bug**
I set both Server and Local folder mapping to root ("/") on both Firefox and Chrome. First I synced my Firefox bookmarks to a Nextcloud server and there were no problems. I can see the same bookmarks folder structure on the server as in Firefox. 
On Chrome I set to "Always overwrite and revert local changes". After syncing, the Chrome bookmarks were intact, but a new folder "Floccus (my.account@nextcloud.server)" was created under "Bookmarks bar" folder, with all bookmarks from the server inside this new folder. I expected to mirror the Firefox folder structure on Chrome.

**To Reproduce**
1. Go to 'Settings' on Chrome
2. Click on 'Folder mapping'
3. Set 'Server folder' and 'Local folder' to /.
4. Click on 'Sync behavior' and set 'Always overwrite and revert local changes'.
5. Scroll down and click 'SAVE'.
6. Open Floccus extension and click 'SYNC NOW'.
7. Open the Bookmark Manager (Ctrl-Shift-O) and inspect the bookmark folder structure.

**Expected behavior**
I expect the bookmark folder structure in Chrome will be the same as on the Nextcloud server starting from the root folder.

**Desktop:**
 - OS: Windows 10 Enterprise build 17763
 - Browser Google Chrome
 - Browser Version 85.0.4183.102
 - Floccus version: 4.3.0
 - Floccus sync method: nextcloud folders

**Server:**
 - OS: Debian 4.19
 - Nextcloud version: 19.0.0
 - Bookmarks app version: 3.3.4

**Comment by marcelklehr** [comment] 2020-09-15 10:54
> Set 'Server folder' and 'Local folder' to /.

Did you actually set the local folder or was it set already and you didn't change it? There's a bug in the latest version that shows the root folder set as local folder, when nothing is set.

**Comment by kotliary** [comment] 2020-09-15 19:14
I believe in Chrome it was root folder from the beginning, but I also clicked on the folder icon, then "Untitled folder" to make sure.
In Firefox, by default the "Floccus (...)" folder was selected, I changed in to root and it worked.
Thanks

**Comment by kotliary** [comment] 2020-09-18 18:26
You closed the question, but what is a possible solution? Do you think this issue is related to the bug you've mentioned? Do you have a plan to fix it? 
Again, it works with Firefox, but not with Chrome. I tried on multiple computers.
Thank you.

**Comment by marcelklehr** [comment] 2020-09-19 10:31
I'm sorry I mistakenly thought the issue was resolved.

**Comment by Baldomo** [comment] 2020-10-30 11:03
This bug is still present in floccus 4.4.4

**Comment by marcelklehr** [comment] 2020-10-30 12:12
Confirmed. patch incoming.

**Comment by marcelklehr** [comment] 2020-10-31 07:19
Actually, scratch that I cannot reproduce this with v4.4.4

**Comment by ParadingLunatic** [comment] 2020-11-01 16:42
The strange thing is, I only recently started having this issue in Firefox.  I can sync to NextCloud fine, but I get the same issue as was referenced in #715 when I try to synch from Nextcloud.  I'm not sure what suddenly started causing the issue.

**Comment by ParadingLunatic** [comment] 2020-11-02 18:26
The 4.4.5 update has resolved the issue for me.

**Comment by Baldomo** [comment] 2020-11-02 20:54
Same here

**Comment by marcelklehr** [comment] 2020-11-02 21:06
Thanks for the feedback, everyone. I was able to reproduce this after all and have pushed the fix. :pray:

**Closed by marcelklehr** 2020-11-02 21:06 UTC
Labels: bug
