### ISSUE TITLE
Bug: Bookmarks get Duplicated

### ISSUE THREAD

**Issue by gohrner** [marcelklehr/floccus#231] opened 2019-02-14 08:49 UTC
Floccus 3.2.4 / Chromium 71.

Floccus dropped / deleted my XBEL-on-WebDAV account during some update (it should not silently do so, but that's another story...), so I had to recreate it.

Afterwards Floccus duplicated about half of my bookmark entries. The duplicates were identical except for a present or missing trailing slash in the URL. (I'm not sure if the original URLs had a trailing slash or were lacking it.)

Possibly, this bug was introduced by the introduction of a new URL normalisation library I read about in the Changelog? ("FIX: Use a different URL normalization library")

It was quite some work to clean up the mess afterwards... :-(

**Comment by marcelklehr** [comment] 2019-02-14 13:33
Hey,

I'm sorry you had to go through that. The cause of this indeed appears to be the changed normalization algorithm. The old algorithm apparently always removed trailing slashes, which made floccus treat `http://google.com/foo/` the same as `http://google.com/foo` (this is not a good idea, but that's a separate point). The algorithm had other problematic properties, which forced me to switch to a different one.

The new algorithm is more gentle and doesn't butcher URLs so they're unusable in the worst case. The downside of this is that butchered URLs that went through the old algorithm are treated as different from the unbutchered URLs, which causes semantic duplicates, i.e. two bookmarks that (in most cases) eventually resolve to the same web page even though they have different URLs.

Sorting this out is a one-time thing as the problem resulted from changing the normalization algorithm, not from syncing in itself. I'll try and come up with a fix for this, though, as it is indeed quite cumbersome to sort this out.

**Comment by Tank-Missile** [comment] 2019-02-14 16:13
Ah, that explains why I'm seeing duplicate bookmarks with incorrect URLs. I might just have to nuke everything in my bookmarks app and start over.

**Comment by marcelklehr** [comment] 2019-02-14 16:14
You can also wait for the next release which should sort out the butchered URLs

**Closed** 2019-02-14 16:50 UTC
Labels: bug

**Comment by marcelklehr** [comment] 2019-02-15 17:42
Did that help?
